### ISSUE TITLE
Aitchison Distance Matrix

### ISSUE THREAD

**Issue by orcuttlab** [ggloor/CoDaSeq#3]
Hello - I am copying and pasting from the CodaSeq.rmd and page 11 of the primer:

# we are doing Euclidian distance (the default) on the log-ratio values
# the log-ratio values are linearly different, which is required for accurate
# use of Euclidian distance
# this is called an Aitchison distance (by some) and is the valid way to determine
# distance for compositional data
# this generates a matrix of distances between each pair of samples
dd <- dist(d.n0.clr)

Is my understanding correct that using the "dist" function in the compositions library on a CLR transformed count table will compute the Aitchison distance between samples and produce a matrix of these distances?

**Comment by ggloor** [comment]
yes that is correct

**Comment by mbaloza** [comment]
Hello @ggloor ,

dose dist function calculates Aitchison distance by default without specifying the method? For example dd <- dist(d.n0.clr, method="Aitchison "). Because R-documentation doesn't say anything about dist function.

Thanks

**Comment by ggloor** [comment]
Yes, that is correct. By default, and design the distance function is the Euclidian distance of the log-ratio transform which is the Aitchison distance
